### ISSUE TITLE
How to inherit python packages from system-wide?

### ISSUE THREAD

**Issue by suliveevil** [brunoarine/org-similarity#6] opened 2022-12-27 07:33 UTC
I have numpy pandas packages installed on system, how to inherit that instead of install another copy to venv? Thank you very much.

**Comment by brunoarine** [comment] 2022-12-27 13:19
The way I'm using the Python backend makes it a bit hard to use another venv.

One dirty solution would be the following: 

1) Clone the repo, go to its directory.
2) Activate the venv you want to use (or do nothing if you prefer to use your system environment), and install the `orgsimilarity` package: 

```sh
python3 -m pip install .
```

3) Point `org-similarity-python-interpreter` to another virtual environment's executable:

```lisp
(setq org-similarity-python-interpreter "path/to/python/executable/in/another/venv")
```

Let me know if that works for you.

**Comment by suliveevil** [comment] 2022-12-27 13:32
Seems some of my org files are not using utf-8 https://github.com/brunoarine/org-similarity/issues/7

I will test this after #7 solved.

Thank you so much.

**Comment by brunoarine** [comment] 2022-12-28 03:04
Duplicate of #8

**Closed by brunoarine** 2022-12-28 03:04 UTC
Labels: question
